[build]
    command = "hugo"
    publish = "public"
    functions = "functions"

[context.production.environment]
    HUGO_VERSION = "0.109.0"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"
